{% set data=load_setup_py_data() %}

package:
  name: reference_data
    version: {{ data.version }}

source:
  path: ../../

build:
  number: 0

requirements:
  build:
    - python {{ python }}
    - versionpy
    - pyyaml
  run:
    - python {{ python }}
    - versionpy
    - pyyaml

test:
  imports:
    - reference_data.api

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  summary: {{ data['description'] }}
